name: Deploy Python App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Python app
      run: |
        nohup python app.py &

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static  # Directory to deploy

    - name: Stop the Python app
      run: |
        pkill -f app.py
