name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install setuptools
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build static content
      run: |
        python app.py  # This step should generate your static files in the static directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static  # Directory to deploy, ensure this contains index.html and other static files
